# CAT-II ASSIGNMENT(INHERITANCE,EXCEPTION HANDLING & NUMPY)

# INHERITANCE IN PYTHON



# SINGLE INHERITANCE


In [46]:
# single inheritance using protected access modifier
class emp:
    def __init__(self,name,income):
        #protected data members initialization
        self._name=name
        self._income=income
class hr(emp):
    def display(self):
        print("NAME:",self._name)
        print("INCOME",self._income)
    def dec(self):
        print('I AM HR CLASS')
hrobj=hr('VK',100000000)
hrobj.display()
hrobj.dec()

NAME: VK
INCOME 100000000
I AM HR CLASS


# MULTI-LEVEL INHERITANCE

In [1]:
class gfather:
    gfname='mr_hacker'
    gfage=18
class father(gfather):
    fname='master_hacker'
    fage=5
class son(father):
    sname='baby_hacker'
    sage=1
sobj=son()
print(sobj.gfname,"\n",sobj.gfage)


mr_hacker 
 18


# MULTIPLE INHERITANCE

In [9]:
class father:
    fname='mr_hacker'
    fage=18
class mother:
    mname='mrs_hacker'
    mage=13
class son(father,mother):
    sname='master_hacker'
    sage=5
sobj=son()
print("FATHER DETAILS:")
print(sobj.fname,"\n",sobj.fage)
print("\n")
print("MOTHER DETAILS:")
print(sobj.mname,"\n",sobj.mage)

FATHER DETAILS:
mr_hacker 
 18


MOTHER DETAILS:
mrs_hacker 
 13


# HEIRARCHIAL INHERITANCE

In [14]:
class university:
    uid=100
    uname="XYZ UNIVERSITY(AUTONOMOUS)"
class arts(university):
    aid=198
    aname="XYZ SCHOOL OF ARTS & SCIENCE"
class engg(university):
    eid=298
    ename="XYZ ENGINEERING COLLEGE"
class medical(university):
    mid=398
    mname="XYZ MEDICAL COLLEGE & HOSPITAL"
class arch(university):
    arid=498
    arname="XYZ SCHOOL OF ARCHITECTURE"
eobj=engg()
print(eobj.eid,"\n",eobj.ename)


298 
 XYZ ENGINEERING COLLEGE


# HYBRID INHERITANCE

In [ ]:
class gfather:
    def __init__(self,gfname):
        self.gfname=gfname
class father(gfather):    
    def __init__(self,fname):
        self.fname=fname
class mother:
    def __init__(self,mname):
        self.mname=mname;
class son(gfather,father,mother):
    def __init__(self,sname):
        self.sname=sname
#here gfather inherits father and father in turn inherits son so ,all the 3 classes follow multi-level inheritance.
#in another way we interpret that son's inheritance also involves mother.
#so in another way son is multiple inherutance more than one class(ie., father and mother)



#the above inheritance involves more than one type of inheritance then this inheritance is called as HYBRID INHERITANCE.

# ACCESS MODIFIERS

In [2]:
#private inheritance
class emp:
    def __init__(self,eid,name):
        self.__eid=eid
        self.__name=name
e1=emp(1,'HR')
e1.__eid
# hence private members cannot be accessed outside the class

AttributeError: 'emp' object has no attribute '__eid'

In [3]:
#private data members initialization
class emp:
    def __init__(self,emid,name):
        self.__eid=emid #.__ is used for private datamember initialization
        self.__ename=name
e1=emp(1,"VK")

# protected data members initialization
class job:
    def __init__(self,name,role):
        self._name=name # ._ is used for initializing data members in protected mode
        self._role=role
    def displaydata(self):
        print("name:",self._name)
        print("role:",self._role)
class hr(job):
    print("I AM USED ONLY FOR OBJECT DECLARATION")
o1=hr('VK','FOUNDER') #object of derived class can initialize data memebers of base class
o1.displaydata()



        



I AM USED ONLY FOR OBJECT DECLARATION
name: VK
role: FOUNDER


In [7]:
#public data members initialization
class emp:
    def __init__(self,name,height,weight):
        self.sname=name # all data members are public by default 
        self.sheight=height # . is used to initialize public data members
        self.sweight=weight
    def display(self):
        print("NAME:",self.sname)
        print("HEIGHT:",self.sheight)
        print("WEIGHT:",self.sweight)
o1=emp('VK',178.7,73.5)
o1.display()

NAME: VK
HEIGHT: 178.7
WEIGHT: 73.5


# NUMPY AGGREGATIONS

In [1]:
import numpy as np
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np.max(x),np.min(x),np.sum(x))

12 1 78


In [2]:
m=np.random.randint(1,100,(3,4))
print(m)
print(m.sum())
print("sum row-wise:",np.sum(x,axis=1))
print("sum col-wise:",np.sum(x,axis=0))
print("max element of each col:",np.max(x,axis=0))
print("min element of each col:",np.min(x,axis=0))


[[55 30 95 31]
 [72 69 29 66]
 [76 82 63 84]]
752
sum row-wise: [10 26 42]
sum col-wise: [15 18 21 24]
max element of each col: [ 9 10 11 12]
min element of each col: [1 2 3 4]


In [3]:
import numpy as np
print(np.product([[1,2],[3,4]]))
print(np.mean([[2,4],[6,8]]))
print(np.std([[2,4],[6,8]]))
print(np.var([[2,4],[6,8]]))
x=np.array([[2,4],[6,8]])
print(np.argmax([1,2,3,4]))
print(np.argmin([1,2,3,4]))
b=np.array([True,True,True,False])
print(np.all(b))
print(np.any(b))
print(np.median([1,2,3,4,5]))

24
5.0
2.23606797749979
5.0
3
0
False
True
3.0


# COMPARISION,MASKS AND BOOLEAN ARRAYS IN NUMPY

In [4]:
#boolean operations
import numpy as np
x=np.array([1,2,3,4,5])
print(x<3)
print(x>3)
print(x<=3)
print(x>=3)
print(x!=3)
print(x==3)

[ True  True False False False]
[False False False  True  True]
[ True  True  True False False]
[False False  True  True  True]
[ True  True False  True  True]
[False False  True False False]


In [5]:
2*x==(x**2)

array([False,  True, False, False, False])

In [6]:
bool(42 and 0)

False

In [7]:
A=np.array([1,0,1,0,1,1],dtype=bool)
B=np.array([1,1,1,0,1,0],dtype=bool)

In [13]:
A&B #and operation

array([ True, False,  True, False,  True, False])

In [9]:
A|B #or operation

array([ True,  True,  True, False,  True,  True])

In [11]:
A!=B # not operation

array([False,  True, False, False, False,  True])

In [12]:
A^B # xor opeartion

array([False,  True, False, False, False,  True])

In [14]:
np.all(A) # checks if all values of A are true

False

In [16]:
np.any(A) # checks if any of the values of A is true

True

# EXCEPTION HANDLING

In [17]:
#zero division error
def fun(a,b):
    try:
        c=a+b/(a-b)
    except ZeroDivisionError:
        print("Error due to divided by 0")
        
    else:
        print(c)
    finally:
        print("error handling learnt succesfully")
fun(1,1)      

    


Error due to divided by 0
error handling learnt succesfully


In [6]:
cgpa=9.2
try:
    if(cgpa>8.5):
        print("distinction")
except SyntaxError:
    print("syntax error")



distinction


In [11]:
list1 = ['x',1, 2, 3,-9.6]
try: 
    print ("Second element =",list1[1])
    print ("Sixth element =",list1[5]) #trying to access out of range element
  
except:
    print ("An error occurred")

Second element = 1
An error occurred


In [22]:
def func1(a , b):
    try:
        c = ((a+b) / (a-b))
    except ZeroDivisionError:
        print ("dividing a/b is 0")
    else:
        print (c)  
        
func1(1,1)
func1(2,1)

dividing a/b is 0
3.0


In [25]:
try:
    raise NameError("Hi there") # Raise Error
except NameError:
    print ("An exception")
    


An exception
